{% set version = "0.4.2" %}

package:
  name: vega
  version: {{ version }}

source:
  fn: vega-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/v/vega/vega-{{ version }}.tar.gz
  md5: 1b5ba6ce77d4c240f6dde55cb8df5dd9

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - jupyter
    - jupyter_client >=4.2

  run:
    - python
    - ipython
    - jupyter

test:
  imports:
    - vega

about:
  home: https://github.com/vega/ipyvega
  license: BSD-3-Clause
  summary: 'An IPython/Jupyter widget for Vega and Vega-Lite'

extra:
  recipe-maintainers:
    - jakevdp
    - ellisonbg
    - domoritz
